config/routes.rb
Rails.application.routes.draw do
 resources :tasks do
  member do
    put :change
  end
end
resources :tasks
devise_for :users

root 'pages#home'

get 'about' => "pages#about"

get 'home' => "pages#home"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to tasks_path
  	end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state: "to_do")
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: '成功创建任务。' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: '成功更新任务。' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: '成功删除任务。' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    redirect_to tasks_path, notice: "任务已经更新！"
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Stukdo</a> -->
      <%= link_to "<i class='fa fa-paw'></i> Stukdo".html_safe, root_path, class: "navbar-brand"%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
        <li><%= link_to "关于", about_path %></li>
       <li><%= link_to "<i class='fa fa-sign-in'></i>登录".html_safe, new_user_session_path %></a></li>
        <% else %>
        <li><%= link_to "任务", tasks_path%></li>
        <li><%= link_to "设定", edit_user_registration_path%>
        <li><%= link_to "<i class='fa fa-sign-out'></i>退出".html_safe, destroy_user_session_path, method: :delete%>
        <% end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StukdoCn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Stukdo是什么？</h1>

<p>Stukdo是一个网络版的Smart Todo List。 它是用Ruby On Rails书写的，一个轻量级的To Do list，它能使你的生活更加简单舒适。</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-paw"></i> 欢迎光临！</h1>
  <p>Stukdo是一个在线的任务管理器，帮助您安排手头上的工作，让您的生活更加方便舒适！</p>
  <p><%= link_to "免费使用!", new_user_registration_path, class: "btn btn-primary btn-lg"%></p>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html:{class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
<%= f.input :content, label: false, required: true, autofocus: true, input_html:{class: "form-control"}, placeholder: "任务内容"%>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/tasks/_task.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<%= link_to edit_task_path(task) do %>
		Created <%= time_ago_in_words(task.created_at)%> ago
		<% end %>
		<%= link_to "x", task_path(task), method: :delete, data: {confirm: "您确定吗?"}, class: "pull-right" %>
	</div><!--end of panel-heading-->
	<div class="panel-body"><%=task.content%></div>
	<div class="panel-footer text-center">
		<% if task.state == "doing"%>
		<div class="btn-group btn-group-justified">
			<%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-info btn-md btn-block"%>
			<%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info btn-md btn-block"%>
		</div>
		<% elsif task.state == "done"%>
		<%= link_to "<i class='fa fa-arrow-left'></i>".html_safe,  change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block"%>
		<% else %>
		<%= link_to "<i class='fa fa-arrow-right'></i>".html_safe,
		change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block"%>
		<%end%>
	</div>
</div>

app/views/tasks/edit.html.erb
<h1>修改任务</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-md-4">
    <h1 class="text-center">需要做的任务</h1>
    <%= render @to_do%>
  </div>

  <div class="col-md-4">
    <h1 class="text-center">正在做的任务</h1>
    <%= render @doing%>
  </div>

  <div class="col-md-4">
    <h1 class="text-center">完成的任务</h1>
    <%= render @done%>
  </div>

</div>

<%= link_to '新任务', new_task_path %>

app/views/tasks/new.html.erb
<h1 class="text-center">新任务</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Content:</strong>
  <%= @task.content %>

</p>
<p>
  <strong>State:</strong>
  <%= @task.state%>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>